### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by wkrueger** [wkrueger/tax-sample#1]
An overview of the pending tasks in the map and its completion.

🏃‍♂️ = in progress

  - Tax logic inner (source + coverage)
    - [ ] IEC 🏃‍♂️
    - [ ] IST 🏃‍♂️
    - [ ] ISC
  - "Outer" logic
    - [ ] The whole transaction
    - [ ] Fast-access state (redis)
    - [x] Import the typedefs
  - Server setup
    - [x] Create cassandra schema
    - [ ] Coverage reports (integrate a service)
    - [ ] Disposable state for test enviroment (create and remove temp data) 🏃‍♂️
    - [ ] Top-level routes
      - [ ] Input validation
  - Client-side
    - [ ] Initial setup (css lib, structure)
    - [ ] Transaction list
    - [ ] Transaction detail
